/**
 * @license Copyright 2026 Otto SPDX-License-Identifier: Apache-2.0
 */

import { describe, expect, it } from 'vitest';
import {
  ALL_AGENT_PROFILES,
  BASE_AGENT_PROFILES,
  COMMON_EXPERT_PROFILES,
  DEPARTMENT_AGENT_PROFILES,
  DEPARTMENT_IDS,
  ENTERPRISE_CEO_PROFILE,
  ENTERPRISE_WORK_PROFILE,
  PERSONAL_OTTO_PROFILE,
  getDepartmentAgentProfiles,
  getEnterpriseAgentProfiles,
  getPersonalAgentProfiles,
  setAutoGeneratedAgentProfiles,
} from './departmentAgents.js';

const FIXED_AGENT_IDS = [
  'otto-enterprise-work',
  'ppt',
  'meeting',
  'doc',
  'sheet',
  'pdf',
  'dataviz',
  'research',
  'copy',
];

describe('fixed Agent profile catalog', () => {
  it('exposes exactly 9 fixed Agents', () => {
    expect(BASE_AGENT_PROFILES.map((profile) => profile.id)).toEqual(FIXED_AGENT_IDS);
    expect(ALL_AGENT_PROFILES).toBe(BASE_AGENT_PROFILES);
    expect(ALL_AGENT_PROFILES).toHaveLength(9);
    expect(COMMON_EXPERT_PROFILES).toHaveLength(8);
  });

  it('uses the enterprise work Agent as the only foundational work Agent', () => {
    expect(ENTERPRISE_WORK_PROFILE).toMatchObject({
      id: 'otto-enterprise-work',
      scope: 'base',
      department: null,
    });
    expect(PERSONAL_OTTO_PROFILE).toBe(ENTERPRISE_WORK_PROFILE);
    expect(ENTERPRISE_CEO_PROFILE).toBe(ENTERPRISE_WORK_PROFILE);
  });

  it('returns the same fixed catalog for personal and enterprise modes', () => {
    expect(getPersonalAgentProfiles()).toBe(BASE_AGENT_PROFILES);
    expect(getEnterpriseAgentProfiles('company_owner')).toBe(BASE_AGENT_PROFILES);
    expect(getEnterpriseAgentProfiles('member', 'marketing')).toBe(BASE_AGENT_PROFILES);
  });

  it('keeps department Agents removed from the runtime catalog', () => {
    expect(DEPARTMENT_IDS).toHaveLength(0);
    expect(DEPARTMENT_AGENT_PROFILES).toHaveLength(0);
    expect(getDepartmentAgentProfiles('marketing')).toHaveLength(0);
    expect(ALL_AGENT_PROFILES.every((profile) => profile.scope !== 'department')).toBe(true);
    expect(ALL_AGENT_PROFILES.every((profile) => profile.department === null)).toBe(true);
  });

  it('does not append auto-generated Skill profiles to the fixed Agent catalog', () => {
    setAutoGeneratedAgentProfiles([{
      id: 'auto-report',
      name: 'Auto Report',
      tagline: 'Generated profile',
      scope: 'base',
      department: null,
      skills: ['auto-report'],
      systemPrompt: 'Generated system prompt that should not enter the fixed catalog.',
    }]);

    expect(getPersonalAgentProfiles().map((profile) => profile.id)).toEqual(FIXED_AGENT_IDS);
    expect(getEnterpriseAgentProfiles('member').map((profile) => profile.id)).toEqual(FIXED_AGENT_IDS);
  });

  it('keeps ids stable and system prompts private', () => {
    const ids = ALL_AGENT_PROFILES.map((profile) => profile.id);

    expect(new Set(ids).size).toBe(ids.length);
    for (const id of ids) expect(id).toMatch(/^[a-z0-9-]+$/);
    for (const profile of ALL_AGENT_PROFILES) {
      expect(Array.isArray(profile.skills)).toBe(true);
      expect(profile.systemPrompt.trim().length).toBeGreaterThan(40);
      expect(profile).not.toHaveProperty('kickoff');
    }
  });
});
