/**
 * @license Copyright 2026 Otto SPDX-License-Identifier: Apache-2.0
 */

import { describe, expect, it } from 'vitest';
import {
  ALL_AGENT_PROFILES,
  BASE_AGENT_PROFILES,
  COMMON_EXPERT_PROFILES,
  DEPARTMENT_AGENT_PROFILES,
  DEPARTMENT_IDS,
  ENTERPRISE_CEO_PROFILE,
  ENTERPRISE_WORK_PROFILE,
  PERSONAL_OTTO_PROFILE,
  getDepartmentAgentProfiles,
  getEnterpriseAgentProfiles,
  getPersonalAgentProfiles,
  setAutoGeneratedAgentProfiles,
} from './departmentAgents.js';

const COMMON_EXPERT_IDS = [
  'ppt',
  'meeting',
  'doc',
  'sheet',
  'pdf',
  'dataviz',
  'research',
  'copy',
];

describe('fixed Agent profile catalog', () => {
  it('keeps exactly 9 visible Agents for every identity with the matching foundation first', () => {
    const expectedByIdentity = [
      [getPersonalAgentProfiles(), 'otto-personal'],
      [getEnterpriseAgentProfiles('company_owner'), 'otto-enterprise-ceo'],
      [getEnterpriseAgentProfiles('company_admin'), 'otto-enterprise-ceo'],
      [getEnterpriseAgentProfiles('manager'), 'otto-enterprise-work'],
      [getEnterpriseAgentProfiles('member', 'marketing'), 'otto-enterprise-work'],
    ] as const;

    for (const [profiles, foundationId] of expectedByIdentity) {
      expect(profiles.map((profile) => profile.id)).toEqual([
        foundationId,
        ...COMMON_EXPERT_IDS,
      ]);
      expect(profiles).toHaveLength(9);
    }

    expect(BASE_AGENT_PROFILES).toBe(getPersonalAgentProfiles());
    expect(COMMON_EXPERT_PROFILES).toHaveLength(8);
  });

  it('keeps the three server-whitelisted foundational profiles as independent objects', () => {
    expect(PERSONAL_OTTO_PROFILE).toMatchObject({
      id: 'otto-personal',
      name: 'Otto',
      department: null,
    });
    expect(ENTERPRISE_CEO_PROFILE).toMatchObject({
      id: 'otto-enterprise-ceo',
      name: 'CEO Agent',
      department: null,
    });
    expect(ENTERPRISE_WORK_PROFILE).toMatchObject({
      id: 'otto-enterprise-work',
      scope: 'base',
      department: null,
    });
    expect(PERSONAL_OTTO_PROFILE).not.toBe(ENTERPRISE_CEO_PROFILE);
    expect(PERSONAL_OTTO_PROFILE).not.toBe(ENTERPRISE_WORK_PROFILE);
    expect(ENTERPRISE_CEO_PROFILE).not.toBe(ENTERPRISE_WORK_PROFILE);

    expect(ALL_AGENT_PROFILES.map((profile) => profile.id)).toEqual([
      'otto-personal',
      'otto-enterprise-ceo',
      'otto-enterprise-work',
      ...COMMON_EXPERT_IDS,
    ]);
    expect(ALL_AGENT_PROFILES).toHaveLength(11);
  });

  it('keeps department Agents removed from the runtime catalog', () => {
    expect(DEPARTMENT_IDS).toHaveLength(0);
    expect(DEPARTMENT_AGENT_PROFILES).toHaveLength(0);
    expect(getDepartmentAgentProfiles('marketing')).toHaveLength(0);
    expect(ALL_AGENT_PROFILES.every((profile) => profile.scope !== 'department')).toBe(true);
    expect(ALL_AGENT_PROFILES.every((profile) => profile.department === null)).toBe(true);
  });

  it('does not append auto-generated Skill profiles to the fixed Agent catalog', () => {
    setAutoGeneratedAgentProfiles([{
      id: 'auto-report',
      name: 'Auto Report',
      tagline: 'Generated profile',
      scope: 'base',
      department: null,
      skills: ['auto-report'],
      systemPrompt: 'Generated system prompt that should not enter the fixed catalog.',
    }]);

    expect(getPersonalAgentProfiles().map((profile) => profile.id)).toEqual([
      'otto-personal',
      ...COMMON_EXPERT_IDS,
    ]);
    expect(getEnterpriseAgentProfiles('company_owner').map((profile) => profile.id)).toEqual([
      'otto-enterprise-ceo',
      ...COMMON_EXPERT_IDS,
    ]);
    expect(getEnterpriseAgentProfiles('member').map((profile) => profile.id)).toEqual([
      'otto-enterprise-work',
      ...COMMON_EXPERT_IDS,
    ]);
  });

  it('keeps ids stable and system prompts private', () => {
    const ids = ALL_AGENT_PROFILES.map((profile) => profile.id);

    expect(new Set(ids).size).toBe(ids.length);
    for (const id of ids) expect(id).toMatch(/^[a-z0-9-]+$/);
    for (const profile of ALL_AGENT_PROFILES) {
      expect(Array.isArray(profile.skills)).toBe(true);
      expect(profile.systemPrompt.trim().length).toBeGreaterThan(40);
      expect(profile).not.toHaveProperty('kickoff');
    }
  });
});
